import "./globals.css";
import { Inter, Dancing_Script } from "next/font/google";
import Navigation from "./common/Navigation";
const inter = Dancing_Script({ subsets: ["latin-ext", "latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
